import type { ExtractedDoc, StandardLexiconEntry } from "@/lib/types";
import { getPanelForCanonical, resolveCanonicalLabName } from "@/lib/standardized";

type MarkdownMeta = {
  originalFileName: string;
  uploadedAtISO: string;
  doctors?: string[];
  facilityName?: string;
};

function escapeMd(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

export function buildDocumentMarkdown(
  doc: ExtractedDoc,
  meta: MarkdownMeta,
  extensions?: StandardLexiconEntry[]
): string {
  const lines: string[] = [];
  lines.push(`# ${doc.artifactSlug ?? "document"}`);
  lines.push("");
  lines.push("| Field | Value |");
  lines.push("| --- | --- |");
  lines.push(`| File name | ${escapeMd(meta.originalFileName)} |`);
  lines.push(`| File type | ${escapeMd(doc.type)} |`);
  lines.push(`| Doctors | ${escapeMd((meta.doctors ?? []).join("; ") || "—")} |`);
  lines.push(`| Hospital / clinic | ${escapeMd(meta.facilityName ?? doc.provider ?? "—")} |`);
  lines.push(`| Date of document | ${escapeMd(doc.dateISO ?? "—")} |`);
  lines.push(`| Date of upload | ${escapeMd(meta.uploadedAtISO)} |`);
  lines.push("");
  lines.push("## Overview");
  lines.push(doc.summary || "—");
  lines.push("");
  lines.push("## Details");

  if (doc.type === "Lab report" && doc.labs?.length) {
    const byPanel = new Map<string, { key: string; value: string; unit?: string; ref?: string; date?: string }[]>();
    for (const l of doc.labs) {
      const canonical = resolveCanonicalLabName(l.name, extensions);
      const panel = getPanelForCanonical(canonical, extensions);
      const row = {
        key: canonical,
        value: l.value,
        unit: l.unit,
        ref: l.refRange,
        date: l.date,
      };
      const list = byPanel.get(panel) ?? [];
      list.push(row);
      byPanel.set(panel, list);
    }
    for (const [panel, rows] of [...byPanel.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
      lines.push(`### ${panel}`);
      lines.push("");
      lines.push("| Standard key | Value | Unit | Reference | Date |");
      lines.push("| --- | --- | --- | --- | --- |");
      for (const r of rows) {
        lines.push(
          `| ${escapeMd(r.key)} | ${escapeMd(r.value)} | ${escapeMd(r.unit ?? "—")} | ${escapeMd(r.ref ?? "—")} | ${escapeMd(r.date ?? "—")} |`
        );
      }
      lines.push("");
    }
  } else if (doc.type === "Prescription" && doc.medications?.length) {
    lines.push("### Medications");
    lines.push("");
    lines.push("| Medication | Dose | Frequency | Route | Notes |");
    lines.push("| --- | --- | --- | --- | --- |");
    for (const m of doc.medications) {
      lines.push(
        `| ${escapeMd(m.name)} | ${escapeMd(m.dose ?? "—")} | ${escapeMd(m.frequency ?? "—")} | ${escapeMd(m.route ?? "—")} | ${escapeMd(m.notes ?? "—")} |`
      );
    }
    lines.push("");
  } else if (doc.type === "Imaging") {
    lines.push("### Imaging");
    lines.push("");
    if (doc.sections?.length) {
      for (const s of doc.sections) {
        lines.push(`#### ${escapeMd(s.title)}`);
        for (const item of s.items ?? []) lines.push(`- ${item}`);
        lines.push("");
      }
    } else {
      lines.push(doc.summary || "—");
      lines.push("");
    }
  } else if (doc.type === "Bill") {
    lines.push("### Billing");
    lines.push("");
    if (doc.sections?.length) {
      for (const s of doc.sections) {
        lines.push(`#### ${escapeMd(s.title)}`);
        for (const item of s.items ?? []) lines.push(`- ${item}`);
        lines.push("");
      }
    } else {
      lines.push(doc.summary || "—");
      lines.push("");
    }
  } else {
    if (doc.sections?.length) {
      for (const s of doc.sections) {
        lines.push(`### ${escapeMd(s.title)}`);
        for (const item of s.items ?? []) lines.push(`- ${item}`);
        lines.push("");
      }
    }
    if (doc.labs?.length) {
      lines.push("### Lab values");
      lines.push("");
      lines.push("| Standard key | Value | Unit |");
      lines.push("| --- | --- | --- |");
      for (const l of doc.labs) {
        const c = resolveCanonicalLabName(l.name, extensions);
        lines.push(`| ${escapeMd(c)} | ${escapeMd(l.value)} | ${escapeMd(l.unit ?? "—")} |`);
      }
      lines.push("");
    }
    if (!doc.sections?.length && !doc.labs?.length) {
      lines.push(doc.summary || "—");
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("_Generated by UMA for organization only. Not medical advice._");
  return lines.join("\n").trim();
}
